[package]
name = "trusty-core"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
embedded-graphics.workspace = true
miniz_oxide = { version = "0.9.0", default-features = false }
embedded-io.workspace = true
log.workspace = true
hypher = "0.1.6"
