[package]
name = "microreader-desktop"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
microreader_core = { path = "../core" }
env_logger = "0.11.8"
log.workspace = true
minifb = "0.28.0"
embedded-graphics.workspace = true
